local funfact = {}


funfact.list = {
    "Also play terraria !",
    "Hi, it's me Chocolife13, Welcome",
    "Fire in the hole !",
    'You should play "Pixel Quest" on roblox',
    "This game can be run on a potato but not GladOS yet",
    "Funfact: this funfact isn't fun at all",
    "I use arch btw",
    "The cake is a lie.",
    "We all love lain",
    "99% of people who read this message have already played this game.",
    "Press Alt+F4 for unlocking sandbox :)",
    "Never gonna give you up, never gonna let you down...",
    "Let him cook.",
    "Bro thinks he's the main character",
    "Source: Trust me bro.",
    "Only in Ohio.",
    "Funfact: The developer is currently crying over a red error line",
    "This game is sponsored by... nobody. We are broke.",
    "Ah shit, here we go again.",
    "Spike planted B",
    "This beautiful menu filled you with determination.",
    "Hopefully Herobrine has been deleted in the last update.",
    "You cannot rest now, there are monsters nearby.",
    "Minecraft Java is better than Bedrock edition",
    "Hopefully the path block is just a Minecraft Bedrock feature",
    "Copilot is not your friend",
    "Technoblade never dies!",
    "Funfact: you can't divide by 0.",
    "This funfact was generated by an AI... or was it?",
    "But nobody came.",
    "It's a beautiful day outside. Birds are singing, flowers are blooming",
    "Go touch grass",
    "Respect your mom",
    "When was the last time you saw water?",
    "I love books And this basement is a true treasure trove",
    "Wait, Android is Linux? Always has been.",
    "Try minecraft 20w14infinite !",
    "~ sweet ~ !",
    "sudo rm -rf /",
    "TempleOS is the best operating system !",
    "This game is written in Lua. Yes, arrays start at 1. Deal with it.",
    "Present day, present time! HAHAHAHA!",
    "If the game crashes, it's a feature to prevent game addiction.",
    "In case I don't see ya, good afternoon, good evening, and good night!",
    "Watch yo jet bro, WATCH YO JET!",
    "yeeeepeeeeeee !!!!",
    "This game is not sponsored by Async foundation",
    "Now with microtransactions!",
    "Check out the farlands!",
    "Blud thinks he's coding the game of the century.",
    "Wake up. Wake up. Wake up. it's just a dream",
    "Anotha one",
    "There are 10 types of people: those who understand binary, and those who don't.",
    "Medic!",
    "You can edit the game yourself in the src folder",
    "I don't believe in horoscopes",
    "day after, day after, day, after",
    "Go back and do your homeworks",
    "Belive in the god of rock",
    "Fun fact: RAM is cheaper than a ram",
    "We don't take ram only money !" 
}


function funfact.random()
    return love.math.random(1, #funfact.list)

end

return funfact